CREATE TABLE User (
	UserID	INTEGER NOT NULL PRIMARY KEY,
	Username	VARCHAR (50),
	Verified	VARCHAR (10),
	Followers	INTEGER
);

CREATE TABLE Tweet (
	TweetID	INTEGER NOT NULL PRIMARY KEY,
	UserID	INTEGER NOT NULL,
	Content	VARCHAR (200),
	FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Likes (
	LikeID	INTEGER NOT NULL PRIMARY KEY,
	UserID	INTEGER NOT NULL,
	TweetID	INTEGER,
	CommentID	INTEGER,
	FOREIGN KEY (CommentID) REFERENCES Comments(CommentID),
	FOREIGN KEY (TweetID) REFERENCES Tweet(TweetID),
	FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE HashtagsInContent (
	HashtagID	INTEGER NOT NULL,
	TweetID	INTEGER,
	CommentID	INTEGER,
	FOREIGN KEY (CommentID) REFERENCES Comments(CommentID),
	FOREIGN KEY (HashtagID) REFERENCES Hashtag(HashtagID),
	FOREIGN KEY (TweetID) REFERENCES Tweet(TweetID)
);

CREATE TABLE Hashtag (
	HashtagID	INTEGER NOT NULL PRIMARY KEY,
	Content	VARCHAR (50)
);

CREATE TABLE Comments (
	CommentID	INTEGER NOT NULL PRIMARY KEY,
	UserID	INTEGER NOT NULL,
	TweetID,
	FK_CommentID,
	Content	VARCHAR (200),
	FOREIGN KEY (TweetID) REFERENCES Tweet(TweetID),
	FOREIGN KEY (FK_CommentID) REFERENCES Comments(FK_CommentID),
	FOREIGN KEY (UserID) REFERENCES User(UserID)
);